/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nameTheMedicine;

import java.io.File;
import java.io.IOException;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.pdfbox.text.PDFTextStripperByArea;

public class Library {

	public static void main(String[] args) throws IOException {
		File file = new File("/home/moyses/ws/java/NameTheMedicine/nameTheMedicine/lib/src/main/resources/med1.pdf");
		System.out.println();
		try (PDDocument document = PDDocument.load(file)) {

			if (!document.isEncrypted()) {

				PDFTextStripperByArea stripper = new PDFTextStripperByArea();
				stripper.setSortByPosition(true);
				
				PDFTextStripper tStripper = new PDFTextStripper();
				tStripper.setStartPage(16);
				tStripper.setStartPage(17);
				
				String pdfFileInText = tStripper.getText(document);

				String lines[] = pdfFileInText.split("\\r?\\n");
				for (String line : lines) {
					System.out.println(line);
				}
			}
		}

	}
}
