/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nameTheMedicine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static nameTheMedicine.util.XmlUtil.asList;
import java.util.Iterator;

import org.junit.jupiter.api.Test;

class LibraryTest {
	@Test
	void someLibraryMethodReturnsTrue() throws Exception {
	
	}
}
